### ISSUE TITLE
Published pipelines link on Examples page goes nowhere

### ISSUE THREAD

**Issue by braymp** [CellProfiler/cellprofiler.github.com#155]
The "Published Pipelines" link on http://cellprofiler.org/examples/ does not link to http://cellprofiler.org/examples/published_pipelines.html.

**Comment by AnneCarpenter** [comment]
Yeah, that link jumps to the Published Pipelines section of the page, though it's not obvious that's what it's doing since it's near the bottom of the page!

The behavior is correct but not pretty, I can't think of an awesome way to solve the problem but perhaps we can start by making the Published Pipelines section of the page has a more prominent title - not sure why it's so subtle. @N3llz

**Comment by N3llz** [comment]
I could link directly to the published pipelines page from there, but for now I can make the text more prominent. Let me know if you want the link changed, I think this will be good though, because IIUC, we still want this chunk of text on the examples page.
