### ISSUE TITLE
Add a blog.

### ISSUE THREAD

**Issue by mcquin** [CellProfiler/cellprofiler.github.com#84]
It would be good to figure out if/how we can use custom subdomains. blog.cellprofiler.org would be preferable over cellprofiler.org/blog.

**Comment by AnneCarpenter** [comment]
Some criteria: 
- searchable from the Forum (forum.cellprofiler.org)
- looks nice

**Comment by mcquin** [comment]
I'm considering using this as the base theme: http://lanyon.getpoole.com/

**Comment by AnneCarpenter** [comment]
It's black and white and read all over.

**Comment by bethac07** [comment]
@karhohs was looking at a few templates, I know he has some specs that he wants (particularly something with a sidebar we can use for tags).  I think the last I heard he liked http://ojs.xyz/solid-jekyll/blog/ but I'm not sure if that's still the front runner.

**Comment by karhohs** [comment]
@0x00b1 was asking me for a template on Tuesday and I suggested http://ojs.xyz/solid-jekyll/blog/ , because I thought it had an attractive look and supported categories. I thought categories might be helpful for organizing blog posts, but maybe lanyon/poole also supports this. As @AnneCarpenter states having Discourse integrated into the template is a goal. Here is a link explaining how a blog post can be tied into a forum post. http://joebuhlig.com/discourse-commenting-for-jekyll/ The comments for a blog post will become a forum topic thread.

**Comment by AnneCarpenter** [comment]
I'd love to see an example of how this works in real life, can you point to a forum/blog pair that take this strategy? The one mentioned has comments on [(this blog post)](http://joebuhlig.com/11/) but I don't see where the content is mirrored on a discourse forum anywhere.

**Comment by AnneCarpenter** [comment]
For the record I'm in favor of a less-busy theme than  http://ojs.xyz/solid-jekyll/blog/ 

Although it makes a difference if you view it in a wide browser window or narrow - I think it's nicer in narrow because the large right hand sidebar goes away and it has a cleaner/simpler look.

**Comment by N3llz** [comment]
it exists: [CP Blog](blog.cellprofiler.org)! Closing this issue :)
